-- ===========================================================
-- 05_signals.sql — researched expansion/contraction signals
-- Real, cited events (~last 18 months). Run AFTER 04_load_data.sql. Run once.
-- ===========================================================

insert into signals (tenant_id, signal_type, direction, impact, headline, detail, magnitude, source, source_url, detected_date) values
  ('25940ee2-14b3-e7eb-af9a-79175871bc69'::uuid, 'New contract', 'Expansion', 'Medium', 'EY aged care contracts surpass $22M', 'EY''s federal aged care advisory contract was extended four times in 2025, lifting related government contracts past $22m.', '$22M', 'The Weekly Source', 'https://www.theweeklysource.com.au/eys-aged-care-contracts-surpass-22m/', '2025-06-01'),
  ('25940ee2-14b3-e7eb-af9a-79175871bc69'::uuid, 'Hiring activity', 'Contraction', 'Medium', 'EY cutting and promoting roles in Australia', 'EY trimmed roles across its ~7,000 Australian workforce in 2025 amid softer tech-consulting demand.', NULL, 'Consultancy.com.au', 'https://www.consultancy.com.au/news/10871/big-four-firm-ey-is-both-axing-and-promoting-new-jobs-in-australia', '2025-03-01'),
  ('af6193e6-be6d-6219-3f0d-c7833c9fca01'::uuid, 'Divestment / disposal', 'Contraction', 'High', 'Offloading ~$4.5B overseas assets, ending global strategy', 'Lendlease is exiting international construction/development and selling overseas assets to refocus on Australia.', '$4.5B', 'Capital Brief', 'https://www.capitalbrief.com/briefing/lendlease-to-offload-4b-assets-and-end-global-strategy-afr-3b3afd4d-d973-4136-b6a4-8b98e2ca3ab7/', '2024-11-01'),
  ('af6193e6-be6d-6219-3f0d-c7833c9fca01'::uuid, 'M&A / takeover', 'Contraction', 'Medium', 'Divests TRX Malaysia retail & office assets', 'Announced divestment of TRX Malaysia assets (~A$400m) under its capital-recycling program.', '$400M', 'Mingtiandi', 'https://www.mingtiandi.com/real-estate/finance/lendlease-swings-to-six-month-loss-of-225m-on-soured-property-valuations/', '2026-02-01'),
  ('1f6e0fd1-019f-fb1a-3e1f-0d01edc8ca28'::uuid, 'Divestment / disposal', 'Contraction', 'High', 'Completes $5.25B fibre asset sale to Vocus', 'TPG completed the sale of fibre infrastructure and its enterprise/government/wholesale fixed business to Vocus, ~560 staff transferring.', '$5.25B', 'Capital Brief', 'https://www.capitalbrief.com/briefing/tpg-telecom-completes-53b-asset-sale-to-vocus-group-ceefcc19-49e2-42a9-8fe0-02c813ec6366/', '2025-07-01'),
  ('8718098a-527b-4b6c-9b98-b4458fed127f'::uuid, 'New contract', 'Expansion', 'Medium', 'Growing data-centre electricity sales', 'Electricity sales up 4% on strong business demand, particularly data centres.', '+4%', 'TipRanks', 'https://www.tipranks.com/news/company-announcements/origin-energy-balances-lng-headwinds-with-data-centre-growth-and-octopus-expansion', '2026-04-01'),
  ('8718098a-527b-4b6c-9b98-b4458fed127f'::uuid, 'Funding secured', 'Expansion', 'Medium', 'Lifts investment in Octopus Energy', 'Invested a further $140m ahead of the planned mid-2026 Octopus/Kraken separation.', '$140M', 'TipRanks', 'https://www.tipranks.com/news/company-announcements/origin-energy-balances-lng-headwinds-with-data-centre-growth-and-octopus-expansion', '2026-04-01'),
  ('8f38dadd-7c89-55b6-1f99-19fefb37f7a2'::uuid, 'Hiring activity', 'Expansion', 'Medium', 'Hires project-finance head in Australia', 'Hired Miles Wadley (ex-HSF) as Melbourne partner and head of Australian project finance.', NULL, 'Law.asia', 'https://law.asia/baker-mckenzie-hires-miles-wadley-australia-project-finance-head-hsf/', '2025-11-01'),
  ('8f38dadd-7c89-55b6-1f99-19fefb37f7a2'::uuid, 'Headcount growth', 'Expansion', 'Low', 'Promotes 23 in Australia', 'Promoted 23 staff in Australia including partner elevations, alongside lateral hiring.', NULL, 'Lawyers Weekly', 'https://www.lawyersweekly.com.au/biglaw/42509-baker-mckenzie-promotes-23-in-australia', '2025-06-01'),
  ('e1fc5eb4-8a5b-7236-6335-e2a703e9627b'::uuid, 'Hiring activity', 'Expansion', 'Low', 'New Australia CEO and APAC leader appointed', 'Aon appointed Kevan Johnston CEO Australia and elevated Jennifer Richards to APAC CEO.', NULL, 'Insurance Business Australia', 'https://www.insurancebusinessmag.com/au/news/breaking-news/aon-announces-pacific-region-leadership-change-556994.aspx', '2025-02-01'),
  ('0c280f3b-420b-a16e-1fee-371fd834321f'::uuid, 'Hiring activity', 'Expansion', 'Medium', 'Strengthens energy & infrastructure with project-finance partner', 'Appointed project-finance specialist Jamie Guthrie as partner in Energy, Resources & Infrastructure.', NULL, 'Gilbert + Tobin', 'https://www.gtlaw.com.au/news/gilbert-tobin-strengthens-energy-and-infrastructure-offering-with-appointment-of-leading-project-finance-partner', '2025-01-01'),
  ('0c280f3b-420b-a16e-1fee-371fd834321f'::uuid, 'Hiring activity', 'Contraction', 'Low', 'Executive partner departs for Corrs', 'Corrs hired G+T executive partner Tim Gordon after 11 years.', NULL, 'Global Legal Post', 'https://www.globallegalpost.com/news/corrs-chambers-westgarth-adds-rival-gilbert-tobins-executive-partner-in-sydney-1568499212', '2025-08-01'),
  ('4ccedd1e-60a3-181f-e979-e667412b2a40'::uuid, 'M&A / takeover', 'Expansion', 'Medium', 'Acquires Botten Levinson, expands in SA', 'Acquired Adelaide''s Botten Levinson Lawyers (eff. 1 Aug 2025); four principals joined as partners.', NULL, 'Law.asia', 'https://law.asia/hwl-ebsworth-acquires-botten-levinson-lawyers/', '2025-08-01'),
  ('4ccedd1e-60a3-181f-e979-e667412b2a40'::uuid, 'M&A / takeover', 'Expansion', 'Medium', 'Acquires Ogilvie Jennings, doubles Hobart team', 'Acquired Tasmanian boutique Ogilvie Jennings (eff. 2 Feb 2026), doubling its Hobart presence.', NULL, 'Lawyers Weekly', 'https://www.lawyersweekly.com.au/biglaw/43544-hwl-ebsworth-acquires-boutique-expands-tassie-presence', '2026-02-01'),
  ('ef0d62eb-d41c-3e17-605a-48f09b2a5dd0'::uuid, 'Headcount growth', 'Expansion', 'Low', 'Record Essential Director Update (14,000+ registrations)', 'Most successful Essential Director Update to date, 14,000+ members registered across 15 locations.', '14,000+', 'AICD', 'https://www.aicd.com.au/content/dam/aicd/pdf/about/annual-reports/2025/annual-report-2025.pdf', '2025-06-30'),
  ('ee191636-7f6e-af3d-302d-74c113885912'::uuid, 'New contract', 'Expansion', 'Medium', 'Launches watsonx on IBM Cloud in Australia', 'Made watsonx AI available to ANZ customers via its Sydney data centre for data sovereignty.', NULL, 'Data Center Dynamics', 'https://www.datacenterdynamics.com/en/news/ibm-adds-watsonx-service-to-ibm-cloud-in-australia-and-new-zealand/', '2025-06-01'),
  ('f6537526-8d4a-6118-71f9-4ab2e55dca48'::uuid, 'Headcount growth', 'Contraction', 'Medium', 'ANZ redundancies amid global layoffs', 'Cut roles in Australia within a global round of ~1,000 redundancies disbanding its global ops team.', NULL, 'Mediaweek', 'https://www.mediaweek.com.au/tiktok-australia-redundancies-global-layoffs/', '2024-07-01'),
  ('f6537526-8d4a-6118-71f9-4ab2e55dca48'::uuid, 'Relocation rumour', 'Contraction', 'Medium', 'Shrinks local ANZ presence as senior execs exit', 'Declined to replace senior Australian execs (GM Lee Hunter and others), signalling a contracting footprint.', NULL, 'Mi3', 'https://www.mi-3.com.au/03-03-2025/tiktok-quietly-shrinks-local-presence-platform-nears-maturation-anz-local-sales-b2b', '2025-03-03'),
  ('4c6661ac-ed4a-ae2a-a16b-632ef7f48800'::uuid, 'New contract', 'Expansion', 'Medium', 'New Double Bay flagship club', 'FLG announced a 1,750sqm Fitness First Double Bay flagship (autumn 2026), part of a $25m NSW investment.', '1,750sqm', 'Australasian Leisure Management', 'https://www.ausleisure.com.au/news/fitness-first-australia-announces-new-flagship-club-for-sydneys-double-bay', '2025-11-01'),
  ('3820eb41-2ab4-b4b1-65b4-c44f33a189bc'::uuid, 'Headcount growth', 'Expansion', 'Low', 'Record FY25 net profit on Escrow.com and Loadshift', 'Revenue up 4.1% to $55.3m; record NPAT $2.2m; Escrow.com +18.8%.', '$55.3M rev', 'NewsnReleases', 'https://newsnreleases.com/2025/07/29/freelancer-1h25-results-record-profit-ai-growth/', '2025-07-29'),
  ('1fdcc7fa-93fd-cb3c-cde5-6c6a9395fbca'::uuid, 'Divestment / disposal', 'Contraction', 'High', 'Wine portfolio sold; Winemakers folds into Vinarchy', 'Pernod Ricard sold its wine business (Jacob''s Creek, St Hugo) to Australian Wine Holdco; merged with Accolade to form Vinarchy.', '~$1.5B', 'The Drinks Business', 'https://www.thedrinksbusiness.com/2025/04/pernod-ricard-completes-wine-sale-to-vinarchy/', '2025-04-30'),
  ('6e4700f4-61c5-563a-cca9-85c980c63685'::uuid, 'M&A / takeover', 'Expansion', 'High', 'Acquiring Better Medical for $159M', 'Agreed to acquire Better Medical (61 clinics, ~800 practitioners) to expand primary care.', '$159M', 'Business News Australia', 'https://www.businessnewsaustralia.com/articles/medibank-private-buys-better-medical-group-for-159m.html', '2025-11-05'),
  ('b5ab3e7a-ff18-1f3b-8731-8ac690862dec'::uuid, 'Other', 'Neutral', 'Low', 'Launches FY26-30 ''FIT for the Future'' strategy', 'Five-year strategy on Financial responsibility, Impact and Trust amid tech and climate disruption.', NULL, 'Standards Australia', 'https://www.standards.org.au/news-archive/november-december-2025', '2025-12-01'),
  ('c2b4e2a5-3dd8-8784-3b6c-26ef6a08b6a4'::uuid, 'M&A / takeover', 'Expansion', 'Medium', 'Completes 3Cloud acquisition (1,000+ Azure experts)', 'Acquired Azure services provider 3Cloud, adding 1,000+ Azure experts and 1,500+ Microsoft certifications.', '1,000+ staff', 'Cognizant', 'https://news.cognizant.com/pressreleases?keywords=acquisition&l=50', '2025-09-01'),
  ('ed18f51a-b591-5b00-bc96-923f57eefb81'::uuid, 'Headcount growth', 'Expansion', 'High', 'Targets doubling Australian headcount to 500', 'Pledged to more than double its Sydney-based APAC headcount to ~500, building account-management and services teams.', '~500 staff', 'ARN', 'https://www.arnnet.com.au/article/3603987/kaseya-aims-at-doubling-aussie-headcount-to-500-by-2025.html', '2024-11-13'),
  ('5ba53a8c-360e-1c9b-4ded-b184cb3c2d2e'::uuid, 'Headcount growth', 'Expansion', 'Medium', 'Morningstar DBRS opens Sydney APAC hub', 'Launched its first APAC regional hub in Sydney, appointing local MDs and building ratings/BD teams.', 'New hub', 'Business Wire', 'https://www.businesswire.com/news/home/20251028544058/en/Morningstar-DBRS-Expands-into-Asia-Pacific-with-New-Australia-Regional-Hub', '2025-10-28'),
  ('a5df3b6c-002a-18c8-6f68-d72fbde8cbd3'::uuid, 'New contract', 'Expansion', 'High', 'Wins $133.6m ADF air-operations sustainment contract', 'Five-year ~$133.6m contract for Air & Space Operations Command & Control sustainment from 1 Aug 2025.', '$133.6M', 'Dept of Defence', 'https://www.defence.gov.au/news-events/releases/2025-09-30/133-million-sustainment-contract-bolster-adf-air-operations', '2025-09-30'),
  ('a5df3b6c-002a-18c8-6f68-d72fbde8cbd3'::uuid, 'Relocation rumour', 'Expansion', 'Medium', 'Seeking larger Canberra lease', 'Reported seeking a 2,000-3,000sqm Canberra lease (ASIO T4) amid rapid government/defence growth.', '2,000-3,000sqm', 'Green Street News', 'https://greenstreetnews.com/article/kbr-growing-rapidly-in-canberra/', '2025-01-01'),
  ('35f83ceb-c14c-04d4-5b76-fb7ec87ff6ee'::uuid, 'New contract', 'Expansion', 'High', 'Wins Logan & Gold Coast Faster Rail main package', 'ActivUs consortium (incl. Acciona) won the design-and-build main package, part of Brisbane 2032 works.', 'Multi-billion', 'Acciona', 'https://www.acciona.com/updates/news/acciona-build-rail-project-queensland-australia', '2025-01-01'),
  ('bc3864fc-b191-efcc-fde9-8448fb8eef2f'::uuid, 'New contract', 'Expansion', 'High', 'Sole developer of final Central Barangaroo stage', 'Secured rights to develop the final stage of the ~$5bn Central Barangaroo precinct after Scentre''s exit.', '~$5B', 'The Urban Developer', 'https://www.theurbandeveloper.com/articles/aqualands-sydney-central-barangaroo-development-approval-nsw', '2025-01-01');
