-- ===========================================================
-- 06_contacts.sql  — researched decision-makers (top 30 tenants)
-- Names/titles/roles are from cited public sources (see notes).
-- Email & mobile intentionally blank — source via Lusha.
-- Run AFTER 04_load_data.sql. Run once.
-- ===========================================================

insert into contacts (tenant_id, full_name, title, role_category, linkedin_url, source, is_primary, notes) values
  ('25940ee2-14b3-e7eb-af9a-79175871bc69'::uuid, 'David Larocca', 'EY Regional Managing Partner and CEO, Oceania', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.ey.com/en_au/people/david-larocca'),
  ('af6193e6-be6d-6219-3f0d-c7833c9fca01'::uuid, 'Tony Lombardo', 'Group Chief Executive Officer and Managing Director', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.lendlease.com/au/about-us/leadership/'),
  ('af6193e6-be6d-6219-3f0d-c7833c9fca01'::uuid, 'Andrew Nieland', 'Group Chief Financial Officer', 'CFO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.lendlease.com/au/about-us/leadership/'),
  ('1f6e0fd1-019f-fb1a-3e1f-0d01edc8ca28'::uuid, 'Inaki Berroeta', 'Chief Executive Officer and Managing Director', 'CEO', 'https://au.linkedin.com/in/i%C3%B1aki-berroeta-9456b27', 'LinkedIn', true, 'Researched (high). Source: https://www.tpgtelecom.com.au/about-us/our-executive-team'),
  ('1f6e0fd1-019f-fb1a-3e1f-0d01edc8ca28'::uuid, 'John Boniciolli', 'Group Chief Financial Officer', 'CFO', NULL, 'Company Website', true, 'Researched (high). Source: https://itwire.com/it-people-news/people-moves/tpg-telecom-appoints-john-boniciolli-as-new-cfo.html'),
  ('8718098a-527b-4b6c-9b98-b4458fed127f'::uuid, 'Frank Calabria', 'Managing Director & Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.originenergy.com.au/about/who-we-are/our-leadership-team/'),
  ('8718098a-527b-4b6c-9b98-b4458fed127f'::uuid, 'Tony Lucas', 'Chief Financial Officer', 'CFO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.originenergy.com.au/about/who-we-are/our-leadership-team/'),
  ('8f38dadd-7c89-55b6-1f99-19fefb37f7a2'::uuid, 'Anne-Marie Allgrove', 'National Managing Partner, Australia', 'Managing Director', NULL, 'Company Website', true, 'Researched (high). Source: https://www.bakermckenzie.com/en/people/a/allgrove-annemarie'),
  ('e1fc5eb4-8a5b-7236-6335-e2a703e9627b'::uuid, 'Kevan Johnston', 'Chief Executive Officer, Australia', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.aon.com.au/australia/newsroom-2025/aon-appoints-kevan-johnston-as-ceo-of-australia'),
  ('e1fc5eb4-8a5b-7236-6335-e2a703e9627b'::uuid, 'Jennifer Richards', 'Chief Executive Officer, Asia-Pacific', 'Country Head', NULL, 'Company Website', true, 'Researched (high). Source: https://www.insurancebusinessmag.com/au/news/breaking-news/aon-announces-pacific-region-leadership-change-556994.aspx'),
  ('0c280f3b-420b-a16e-1fee-371fd834321f'::uuid, 'Sam Nickless', 'Partner and Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.gtlaw.com.au/our-people/sam-nickless'),
  ('0c280f3b-420b-a16e-1fee-371fd834321f'::uuid, 'Danny Gilbert', 'Chairman', 'Other', NULL, 'Company Website', true, 'Researched (high). Source: https://www.gtlaw.com.au/news/gilbert-tobin-announces-evolved-leadership-model-effective-july-2023'),
  ('4ccedd1e-60a3-181f-e979-e667412b2a40'::uuid, 'Kris Hopkins', 'Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.lawyersweekly.com.au/biglaw/39942-hwl-ebsworth-unveils-new-board-of-partners-ceo-and-chief-executive-partner'),
  ('4ccedd1e-60a3-181f-e979-e667412b2a40'::uuid, 'Russell Mailler', 'Chief Executive Partner', 'Other', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.lawyersweekly.com.au/biglaw/39942-hwl-ebsworth-unveils-new-board-of-partners-ceo-and-chief-executive-partner'),
  ('ef0d62eb-d41c-3e17-605a-48f09b2a5dd0'::uuid, 'Mark Rigotti', 'Managing Director & Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.aicd.com.au/leadership/AICD-MD-and-CEO-Mark-Rigotti-GAICD-elected-Chair-of-GNDI.html'),
  ('ee191636-7f6e-af3d-302d-74c113885912'::uuid, 'Nicholas Flood', 'Vice President & Managing Director ANZ, IBM', 'Managing Director', 'https://au.linkedin.com/in/nicholasflood1', 'LinkedIn', true, 'Researched (high). Source: https://asean.newsroom.ibm.com/Nicholas-Flood'),
  ('74ff0ea8-51ce-c12d-3693-8e4186eaeccc'::uuid, 'Harry Moore', 'Chief Executive Officer, First Sentier Group', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.firstsentiergroup.com/news-insights/news/first-sentier-group-announces-appointment-of-new-ceo'),
  ('74ff0ea8-51ce-c12d-3693-8e4186eaeccc'::uuid, 'Ashley Conn', 'Chief Financial and Strategy Officer', 'CFO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.firstsentiergroup.com/news-insights/news/fsi-appoints-ashley-conn-as-chief-financial-and-strategy-officer'),
  ('45058ea5-2325-a1df-73fb-0442d4ffcc83'::uuid, 'Nic Horridge', 'General Manager, Roche Pharmaceuticals Australia', 'Country Head', NULL, 'Company Website', true, 'Researched (medium). Source: https://pharmadispatch.com/news/roche-confirms-the-appointment-of-new-general-manager-for-austra'),
  ('4c6661ac-ed4a-ae2a-a16b-632ef7f48800'::uuid, 'Greg Oliver', 'CEO & Managing Director, Fitness and Lifestyle Group', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.healthclubmanagement.co.uk/health-club-management-features/Interview-Greg-Oliver/38149'),
  ('3820eb41-2ab4-b4b1-65b4-c44f33a189bc'::uuid, 'Matt Barrie', 'Chief Executive Officer & Chairman', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://en.wikipedia.org/wiki/Freelancer.com'),
  ('3820eb41-2ab4-b4b1-65b4-c44f33a189bc'::uuid, 'Dylan Carter', 'Chief Financial Officer', 'CFO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.staffingindustry.com/news/global-daily-news/freelancer-taps-dylan-carter-as-cfo'),
  ('6e4700f4-61c5-563a-cca9-85c980c63685'::uuid, 'David Koczkar', 'Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://theorg.com/org/medibank-private-ltd/org-chart/david-koczkar'),
  ('6e4700f4-61c5-563a-cca9-85c980c63685'::uuid, 'Mark Rogers', 'Group Lead - Chief Financial Officer & Group Strategy', 'CFO', 'https://au.linkedin.com/in/mark-rogers-78058b20b', 'LinkedIn', true, 'Researched (high). Source: https://www.medibank.com.au/livebetter/newsroom/post/medibank_appointsma'),
  ('b5ab3e7a-ff18-1f3b-8731-8ac690862dec'::uuid, 'Rod Balding', 'Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://www.standards.org.au/news/standards-australia-appoints-rod-balding-as-new-chief-executive-officer'),
  ('c2b4e2a5-3dd8-8784-3b6c-26ef6a08b6a4'::uuid, 'Carla Ramchand', 'Managing Director for Australia and New Zealand', 'Managing Director', NULL, 'Company Website', true, 'Researched (high). Source: https://www.consultancy.com.au/news/12108/cognizant-appoints-carla-ramchand-as-managing-director-for-anz-region'),
  ('635dcec5-f7f7-45f6-c894-37086ebbff82'::uuid, 'Prins Ralston', 'Interim Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (high). Source: https://australiancybersecuritymagazine.com.au/acs-appoints-interim-chief-executive-officer/'),
  ('635dcec5-f7f7-45f6-c894-37086ebbff82'::uuid, 'Beau Tydd', 'President', 'President', NULL, 'Company Website', true, 'Researched (high). Source: https://ia.acs.org.au/article/2026/-tech-can-change-lives---acs-president-beau-tydd-on-a-life-in-it.html'),
  ('ed18f51a-b591-5b00-bc96-923f57eefb81'::uuid, 'Daniel Garcia', 'VP & General Manager, APAC', 'Vice President', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.crn.com.au/news/kaseyas-daniel-garcia-on-the-state-of-ma-in-the-anz-it-channel-612997'),
  ('28ae87ae-a7dd-0597-0d49-6b58b1b1308b'::uuid, 'Sylvain Vigneault', 'Country Manager, Australia', 'Country Head', NULL, 'Company Website', true, 'Researched (high). Source: https://www.viatris.com.au/en-au/about-us/our-leadership/sylvain-vigneault'),
  ('33dfe9d8-fc55-2273-fd8d-4f3b830ec6e6'::uuid, 'Chris Colahan', 'Country President, Australia & New Zealand (interim)', 'President', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.insurancenews.com.au/daily/chubb-appoints-australia-country-president-as-kelaher-moves-to-paris'),
  ('57498058-2d64-15ad-000d-e42f4bff493a'::uuid, 'Lynn Kraus', 'Chief Executive Officer', 'CEO', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.auspayplus.com.au/'),
  ('5ba53a8c-360e-1c9b-4ded-b184cb3c2d2e'::uuid, 'Chris Galloway', 'Country Leader, Australia & New Zealand', 'Country Head', 'https://www.linkedin.com/in/chris-galloway-cfa/', 'LinkedIn', true, 'Researched (high). Source: https://www.investordaily.com.au/appointments/53321-morningstar-anz-md-to-depart-new-country-leader-named'),
  ('bc964a1a-a567-405b-daf9-c7f08a993cbc'::uuid, 'Megan Hughes', 'Managing Director and VP of Sales, Asia Pacific & Japan', 'Managing Director', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.hubspot.com/company/management'),
  ('a5df3b6c-002a-18c8-6f68-d72fbde8cbd3'::uuid, 'Nic Maan', 'Vice President, Government Solutions APAC', 'Vice President', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.australiandefence.com.au/business/kbr-appoints-new-lead-for-government-solutions-apac'),
  ('35f83ceb-c14c-04d4-5b76-fb7ec87ff6ee'::uuid, 'Bede Noonan', 'CEO, ACCIONA Australia & New Zealand', 'CEO', 'https://au.linkedin.com/in/bedenoonan', 'LinkedIn', true, 'Researched (high). Source: https://www.acciona.com.au/updates/news/announcement-of-new-ceo-in-australia-and-new-zealand'),
  ('35f83ceb-c14c-04d4-5b76-fb7ec87ff6ee'::uuid, 'Gavin Reymond', 'Managing Director, ACCIONA Energia Australia', 'Managing Director', NULL, 'Company Website', true, 'Researched (high). Source: https://www.acciona.com.au/updates/news/gavin-reymond-appointed-new-managing-director-of-acciona-energia-australia'),
  ('bc3864fc-b191-efcc-fde9-8448fb8eef2f'::uuid, 'Jin Lin', 'Group Managing Director', 'Managing Director', NULL, 'Company Website', true, 'Researched (medium). Source: https://www.aqualand.com.au/team/jin-lin/');
